modLoader="javafml"
loaderVersion="[36,)"

license="All rights reserved"

[[mods]]
modId="ivv"
version="${file.jarVersion}"
displayName="Immersive Vehicles (MTS/IV) - Immersive Vehicles Vanity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-vehicles-vanity"
logoFile="vingette.png"
authors="cowboycosmic"
# laura cute
credits="LauraDarkez2001, HashimIsaPotato and TheOddlySeagull"
description='''
Decorative parts, somewhat-useful vehicles, decoration blocks and more!
'''
