modLoader="javafml"
loaderVersion="[36,)"

license="All rights reserved"

[[mods]]
modId="ivv"
version="${file.jarVersion}"
displayName="Immersive Vehicles (MTS/IV) - Immersive Vehicles Vanity"
displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-vehicles-vanity"
logoFile="vingette.png"
authors="cowboycosmic"
# laura cute
credits="HashimIsaPotato, LauraDarkez2001 and TheOddlySeagull"
description='''
WARNING: Contains Fun!
'''
